services:
  - type: web
    name: expense-tracker-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn config.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings