# render.yaml
services:
  - type: web
    name: expensetracker-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
    staticPublishPath: staticfiles
